import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { NextUIProvider } from "@nextui-org/system";
import "../globals.css";

const lato = Lato({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body className={lato.className}>
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  );
}
