import AdminLayoutContentHeader from "@/components/admin/content-header";
import AddIcon from "@/components/icons/add";
import { Button, CardBody } from "@nextui-org/react";
import type { Metadata } from "next";
import { useTranslations } from "next-intl";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const t_dashboard = useTranslations("Dashboard");

  return (
    <>
      <AdminLayoutContentHeader
        left={<h2 className="font-bold text-lg">{t_dashboard("Title")}</h2>}
        right={<div />}
      />
      <CardBody>{children}</CardBody>
    </>
  );
}
