import AdminLayoutContentHeader from "@/components/admin/content-header";
import AddIcon from "@/components/icons/add";
import { Button, CardBody } from "@nextui-org/react";
import type { Metadata } from "next";
import { useTranslations } from "next-intl";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const t_category = useTranslations("Category");
  const t_form = useTranslations("Form");

  return (
    <>
      <AdminLayoutContentHeader
        left={<h2 className="font-bold text-lg">{t_category("List")}</h2>}
        right={
          <div>
            <Link href={`/${locale}/admin/category/create`}>
              <Button startContent={<AddIcon />} color="primary" variant="light">
                {t_form("Button.Create")}
              </Button>
            </Link>
          </div>
        }
      />
      <CardBody>{children}</CardBody>
    </>
  );
}
