import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import { NextUIProvider } from "@nextui-org/system";
import { ReactNode } from "react";

const lato = Inter({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body className={lato.className}>
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  );
}
