import type { Metadata } from "next";
import { Card } from "@nextui-org/react";
import AdminLayoutSidebar from "@/components/admin/sidebar";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  props: Readonly<{
    children: ReactNode;
  }>,
) {
  const messages = useMessages();

  return (
    <NextIntlClientProvider
      //   locale={params.locale.toString()}
      messages={messages}
    >
      <div className="flex">
        <AdminLayoutSidebar />

        <div className="flex-1">
          <header className="bg-gray-800 text-white py-4 px-6">
            Your Header Content Here
          </header>

          {/*<nav className="bg-gray-200 py-2 px-6">*/}
          {/*  Your Breadcrumb Content Here*/}
          {/*</nav>*/}

          <Card className="px-4" radius={"none"} shadow="none">
            {props.children}
          </Card>
        </div>
      </div>
    </NextIntlClientProvider>
  );
}
